image: registry.anansi.xyz/anansi/javascript-ci-image:latest

stages:
  - prepare
  - static analysis
  - test
  - build
  - deploy

cache:
  paths:
    - ./node_modules
  key: ${CI_JOB_NAME}

install dependencies:
  stage: prepare
  script: npm install
  artifacts:
    paths:
      - ./node_modules
    expire_in: 1h

check dependencies:
  stage: static analysis
  script: ./ci/check-dependencies.sh
  artifacts:
    paths:
      - build/badges/*.svg
    when: always

check duplicate code:
  stage: static analysis
  script: ./ci/check-duplicate-code.sh

lint javascript code:
  stage: static analysis
  script: npm run lint-javascript

lint shell code:
  stage: static analysis
  script: npm run lint-shell

lint Dockerfile:
  stage: static analysis
  script: npm run lint-docker

unit tests:
  stage: test
  script: ./ci/test.sh

coverage:
  stage: test
  script: ./ci/coverage.sh
  artifacts:
    paths:
      - ./build/badges/*.svg
    when: always

build Docker image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  dependencies: []
  only:
    - tags

deploy to swarm:
  stage: deploy
  image: docker:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker stack deploy --with-registry-auth --compose-file=docker-stack-compose.yml ${CI_PROJECT_NAMESPACE}${SERVICE_NAME}
  dependencies: []
  only:
    - tags
  tags:
    - deploy
